> proj<-read.table("C:\\Coursera_exploratory\\household_power_consumption.txt", header=T, sep=";", stringsAsFactors=FALSE, dec=".")
> powerdata <- proj[proj$Date %in% c("1/2/2007","2/2/2007"),]
> time <- strptime(paste(powerdata$Date, powerdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
> subMetering1 <- as.numeric(powerdata$Sub_metering_1)
> subMetering2 <- as.numeric(powerdata$Sub_metering_2)
> subMetering3 <- as.numeric(powerdata$Sub_metering_3)
> globalReactivePower <- as.numeric(powerdata$Global_reactive_power)
> png("plot4.png", width=480, height=480)
> par(mfrow = c(2, 2))
plot(time, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
> png("plot4.png", width=480, height=480)
> plot(time, subMetering1, type="l", ylab="Energy Submetering", xlab="")
> lines(time, subMetering2, type="l", col="red")
> lines(time, subMetering3, type="l", col="blue")
> legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
> plot(time, globalReactivePower, type="l", xlab="time", ylab="Global_reactive_power")
> dev.off()